### PR TITLE
Allow more complex annotations

### PR DESCRIPTION
**Pull request by saraedum**
for example we use the regular expression `{annotation: /\/\/\/ <reference +path="(.*)" *\/>/g}` to
parse the references described in
https://msdn.microsoft.com/en-us/library/bb385682.aspx.

### CODE REVIEW

**Comment by saraedum** [comment]
This needs additional testing code of course but would you accept something like this into upstream?

**Comment by pnevyk** [comment]
Nice use case! Sure I can merge this feature.

Your change breaks old functionality, imho just because it doesn't take separator into account. Original behavior splits the regexp match using separator (default: comma) and these split trimmed items are actual dependencies. In case of RegExp instance in annotation (your feature), separator option should be probably ignored.

And if you added a test of this new feature, it would be super cool. Thanks for the input!

**Comment by pnevyk** [comment]
@saraedum I added feature you requested, it's in version `0.2.1`. I am going to close this PR.

**Comment by saraedum** [comment]
Thanks for taking care of this!

**Pull request closed without merging**
